### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by devdot4** [fizal619/newscraper-pwa#2]
Please update the deprecated readme and include all the latest information about the newscraper app.

Thanks!

**Comment by devdot4** [comment]
Still waiting for the update, thank you.

**Comment by fizal619** [comment]
Will do boss


--
*Fizal Sarif *
*Let's connect on LinkedIn
<https://www.linkedin.com/in/fizalsarif> | 718.764.7747*
*Check out my Projects <http://fizal.me/> or my GitHub
<http://github.com/fizal619> profile too!*
